create table guitar(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR (50) NOT NULL ,
  brand VARCHAR (50) NOT NULL,
  type VARCHAR (50) NOT NULL,
  price INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER before_insert_guitar
  BEFORE INSERT ON guitar
  FOR EACH ROW
  SET new.slug = uuid();
